version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: install flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8
      - run:
          name: run flake8      
          command: |
            . venv/bin/activate
            python -m flake8 --exclude venv
