version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt flake8

      - run:
          name: run flake8
          command: |
            . venv/bin/activate
            python -m flake8 --exclude venv
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test
