version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          command: poetry install
      - run:
          command: poetry run flake8
      - run:
          command: poetry run black --check .
#      - run:
#          command: poetry run pytest
